# architectures
conservative = [1]
batch_norm_pos = [-1, 0, 1]
dropout_rate = [0, 0.25, 0.5]
n_blocks = [1, 3, 5]
network_size = [5, 10, 20]

# training
batch_size = [32]
learning_rate = [1e-4, 1e-5]
