geostrophy: true
boussinesq: false
saturate_online: false
hprop: false

ngrid: 101
grid_max: 100.e+3

dt: 120
nday: 2

rhobar0: 1.2
hh: 8.5e+3
phi0: 0

N0: 0.01
alpha: 0.01
kappa: 1

nray: 60
nray_max: 100

wvl_hor_init: 50.e+3
wvl_ver_init: 5.e+3
direction: 90

dk_init: 1.e-4
dl_init: 1.e-4
r_m_area: 5.e-5
r_init_bounds: [0, 15.e+3]

uv_init_method: sine_homogeneous
u0: 4
r0: 40.e+3
sig_r: 10.e+3