################################################################################
# global parameters
################################################################################
boussinesq = false
show_progress = true
interactive_mean = false
mean_file = 'data/baselines/mean-state.nc'

################################################################################
# time stepping
################################################################################
dt = 120
n_day = 30
dt_output = 7200

################################################################################
# momentum flux calculation
################################################################################
shapiro_filter = true
proj_method = 'discrete'

################################################################################
# vertical grid
################################################################################
n_grid = 101
grid_bounds = [0, 60e3]

################################################################################
# mean state parameters
################################################################################
latitude = 0
rhobar0 = 1.2
H_scale = 7e3
N0 = 0.02

################################################################################
# mean flow initialization
################################################################################
uv_init_method = 'gaussian'
u0 = 4
r0 = 40e3
sig_r = 5e3

################################################################################
# flow parameters
################################################################################
mu = 1e-3
alpha = 1
dissipation = 1

################################################################################
# source and spectrum options (parameters in this section are likely to be used
# by more than one source spectrum type)
################################################################################
source_type = 'gaussians'
epsilon = 1

n_ray_max = 40000
bc_mom_flux = 3e-3
purge = false

wvl_hor_char = 100e3
# wvl_ver_char = 2e3
direction = 0

dk_init = 1e-4
dl_init = 1e-4

r_launch = 15000
dr_init = 250

################################################################################
# 'gaussians' spectrum parameters
################################################################################
c_center = 0 # Peak of Gaussians in phase speed space (m / s).
c_width = 15 # Width if Gaussian is prescribed in phase speed space (m / s).
n_source = 48 # How many ray volumes to discretize the interval into.

################################################################################
# 'desaubies' spectrum parameters
################################################################################
# n_c = 6
# n_omega = 2
# c_bounds = [0, 36]
# omega_bounds = [1e-4, 5e-4]
