################################################################################
# global parameters
################################################################################
boussinesq = false
hprop = false
show_progress = true

################################################################################
# wave-mean interactions
################################################################################
interactive_mean = true
mean_file = 'data/baselines/mean-wind.nc'
saturate_online = false
filter_pmf = true

################################################################################
# time stepping
################################################################################
dt = 120
n_day = 125
dt_output = 7200

################################################################################
# vertical grid
################################################################################
n_grid = 101
grid_bounds = [0, 100e3]

################################################################################
# mean state parameters
################################################################################
phi0 = 0
rhobar0 = 1.2
hh = 7e3
N0 = 0.01

################################################################################
# mean flow initialization
################################################################################
uv_init_method = 'gaussian'
u0 = 4
r0 = 60e3
sig_r = 10e3

################################################################################
# flow parameters
################################################################################
nu = 10
alpha = 1

################################################################################
# source options
################################################################################
source_type = 'gaussians'
epsilon = 1

n_ray_max = 2475
bc_mom_flux = 6e-3

wvl_hor_char = 75e3
direction = 0

dk_init = 1e-4
dl_init = 1e-4

r_launch = 15000
dr_init = 250

################################################################################
# 'gaussians' spectrum parameters
################################################################################
c_center = 0
c_width = 20
n_source = 180
