################################################################################
# global parameters
################################################################################
boussinesq = false
hprop = false

################################################################################
# wave-mean interactions
################################################################################
interactive_mean = true
saturate_online = false
filter_pmf = true

################################################################################
# time stepping
################################################################################
dt = 120
n_day = 50
dt_output = 7200

################################################################################
# vertical grid
################################################################################
n_grid = 101
grid_bounds = [0, 100e3]

################################################################################
# mean state parameters
################################################################################
phi0 = 0
rhobar0 = 1.2
hh = 7e3
N0 = 0.02

################################################################################
# mean flow initialization
################################################################################
uv_init_method = 'gaussian'
u0 = 8
r0 = 60e3
sig_r = 10e3

################################################################################
# flow parameters
################################################################################
nu = 10
alpha = 1

################################################################################
# source options
################################################################################
source_type = 'constant'
spectrum_type = 'gaussians'

n_ray_max = 2500
bc_mom_flux = 5e-3

wvl_hor_char = 50e3
direction = 0

dk_init = 1e-4
dl_init = 1e-4
dm_init = 1e-7

r_launch = 15e3
dr_init = 250

################################################################################
# 'stochastic' source parameters
################################################################################
source_fraction = 0.1

################################################################################
# 'gaussians' spectrum parameters
################################################################################
c_bounds = [-60, 60]
c_center = 20
c_width = 30
n_c = 200