################################################################################
# global parameters
################################################################################
boussinesq = false
show_progress = true
interactive_mean = true
mean_file = 'data/baselines/mean-wind.nc'

################################################################################
# time stepping
################################################################################
dt = 120
n_day = 60
dt_output = 7200

################################################################################
# momentum flux calculation
################################################################################
shapiro_filter = false
proj_method = 'gaussian'
smoothing = 4
tau = 3600

################################################################################
# vertical grid
################################################################################
n_grid = 101
grid_bounds = [0, 60e3]

################################################################################
# mean state parameters
################################################################################
latitude = 0
rhobar0 = 1.2
H_scale = 7e3
N0 = 0.01

################################################################################
# mean flow initialization
################################################################################
uv_init_method = 'gaussian'
u0 = 4
r0 = 40e3
sig_r = 5e3

################################################################################
# flow parameters
################################################################################
mu = 1e-2
alpha = 1
dissipation = true

################################################################################
# source and spectrum options (parameters in this section are likely to be used
# by more than one source spectrum type)
################################################################################
source_type = 'gaussians'
epsilon = 1

n_ray_max = 5000
bc_mom_flux = 3e-3

wvl_hor_char = 200e3
direction = 0

dk_init = 1e-4
dl_init = 1e-4

r_launch = 15000
dr_init = 250

################################################################################
# 'gaussians' spectrum parameters
################################################################################
c_center = 0
c_width = 15
n_source = 72
