################################################################################
# global parameters
################################################################################
boussinesq = false
hprop = false

################################################################################
# wave-mean interactions
################################################################################
interactive_mean = false
mean_file = 'data/extract.nc'
saturate_online = false
filter_pmf = true

################################################################################
# time stepping
################################################################################
dt = 120
n_day = 15
dt_output = 7200

################################################################################
# vertical grid
################################################################################
n_grid = 101
grid_bounds = [0, 100e3]

################################################################################
# mean state parameters
################################################################################
phi0 = 0
rhobar0 = 1.2
hh = 7e3
N0 = 0.02

################################################################################
# mean flow initialization
################################################################################
uv_init_method = 'gaussian'
u0 = 8
r0 = 60e3
sig_r = 10e3

################################################################################
# flow parameters
################################################################################
nu = 10
alpha = 1

################################################################################
# source options
################################################################################
source_method = 'bimodal'
constant_flux = true
n_ray_max = 760
bc_mom_flux = 3e-3

wvl_hor_char = 50e3
wvl_ver_char = 2e3
direction = 0

dk_init = 1e-4
dl_init = 1e-4
dm_init = 2e-7

r_launch = 15e3
dr_init = 500

################################################################################
# 'bimodal' source parameters
################################################################################
n_per_mode = 2
