# ==============================================================================
# global flags
# ==============================================================================
show_progress = false
interactive_mean = false
# prescribed_wind = 

# ==============================================================================
# time stepping
# ==============================================================================
dt = 120
dt_output = 3600
n_day = 2

# ==============================================================================
# vertical grid
# ==============================================================================
grid_bounds = [0, 60e3]
n_grid = 101

# ==============================================================================
# mean state profiles
# ==============================================================================
N0 = 0.02
rho0 = 1.2
boussinesq = false
H_rho = 7e3
latitude = 0

# ==============================================================================
# mean wind initialization
# ==============================================================================
# wind_init_method =
# z0 =
# sigma_uv =
# u0 =
# v0 =

# ==============================================================================
# pseudomomentum flux calculation
# ==============================================================================
shapiro_filter = true
proj_method = 'discrete'

# ==============================================================================
# viscosity and dissipation
# ==============================================================================
mu = 1e-3
dissipation = 1

# ==============================================================================
# ray volumes and propagation
# ==============================================================================
n_ray_max = 48
n_chromatic = -1
epsilon = 1

# ==============================================================================
# source and spectrum (parameters in this section are likely to be used by more
# than one source or spectrum type)
# ==============================================================================
source_type = 'constant'
spectrum_type = 'gaussians'
purge = false

relaunch = false
bc_mom_flux = 3e-3

r_launch = 15e3
dr_init = 250

dk_init = 1e-4
dl_init = 1e-4

wvl_hor_char = 100e3
direction = 0

# ==============================================================================
# 'gaussians' spectrum
# ==============================================================================
c_center = 0
c_width = 15
n_source = 48
