# ==============================================================================
# global flags
# ==============================================================================
show_progress = true
interactive_mean = false
prescribed_wind = 'data/centered/mean-state-descending-jets.nc'

# ==============================================================================
# time stepping
# ==============================================================================
dt = 120
dt_output = 1800
n_day = 60
average_output = true

# ==============================================================================
# vertical grid
# ==============================================================================
grid_bounds = [0, 60e3]
n_grid = 101

# ==============================================================================
# mean state profiles
# ==============================================================================
N0 = 0.02
rho0 = 1.2
boussinesq = false
H_rho = 7e3
latitude = 0

# ==============================================================================
# mean wind initialization
# ==============================================================================
wind_init_method = 'gaussian'
u0 = 4
v0 = 0
z0 = 30e3
sigma_uv = 3e3

# ==============================================================================
# pseudomomentum flux calculation
# ==============================================================================
shapiro_filter = true
proj_method = 'discrete'
# smoothing =

# ==============================================================================
# viscosity and dissipation
# ==============================================================================
mu = 1e-3
dissipation = 1

# ==============================================================================
# ray volumes and propagation
# ==============================================================================
n_ray_max = 1
min_pmf = 1e-8
n_chromatic = -1

# ==============================================================================
# source and spectrum (parameters in this section are likely to be used by more
# than one source or spectrum type)
# ==============================================================================
source_type = 'simple'
spectrum_type = 'gaussians'
purge_mode = 'none'
n_increment = 0

rescale_fluxes = true
dt_launch = 120

r_launch = 5e3
dr_init = 600

dk_init = 1e-4
dl_init = 1e-4

wvl_hor_char = 100e3
direction = 0

n_source = 54
c_max = 50

# ==============================================================================
# 'gaussians' spectrum
# ==============================================================================
c_center = 0
c_width = 25
bc_mom_flux = 2e-3

# ==============================================================================
# 'from_file' spectrum
# ==============================================================================
# spectrum_file: str # Path to saved spectrum.

# ==============================================================================
# 'network' source
# ==============================================================================
# model_path: str # Path where JIT-compiled neural network is saved.
