################################################################################
# global integration settings
################################################################################
propagator_type = 'transient'
source_type = 'constant'
spectrum_type = 'mima'

################################################################################
# input and output
################################################################################
average_output = true
prescribed_mean_file = 'DATA_DIR/input/mean-state.nc'
spectrum_file = 'DATA_DIR/input/spectrum.nc'

################################################################################
# time stepping
################################################################################
dt = 60
dt_output = 240
n_day = 5

################################################################################
# mean state
################################################################################
H_rho = 7e3
latitude = 45
n_grid = 201
N_ref = 0.015
rho_ref = 1.2
tau_nudge = 0
z_max = 60e3
z_min = 5e3

################################################################################
# viscosity and dissipation
################################################################################
dissipation = 1
mu = 1e-3

################################################################################
# gravity wave source and spectrum
################################################################################
c_max = 60
dt_launch = -1
equal_flux = false
extrinsic = true
n_source = 300

################################################################################
# 'transient' propagator
################################################################################
cfl_mode = 'warn'
dr_ghost = 2000
dr_source = 100
dr_max = 10000
dr_min = 50
jitter = 0
logging = true
max_age = 86400
max_age_ghost = 43200
max_age_warning = 86400
max_dt_multiplier = 10
max_overshoot = 1.2
min_cg = -inf
min_flux = 1e-8
n_chromatic = -1
n_increment = 0
n_max = 50000
n_sponge = 5
oob_action = 'delete'
prune_by = 'energy'
r_source = 'data/source-levels.in'
shapiro_filter = true
strict_source = true

################################################################################
# 'stochastic' source
################################################################################
epsilon = 1

################################################################################
# 'mima' spectrum
################################################################################
flux_bc_ex = 0.008
flux_bc_tr = 0.008
cp_width_ex = 35
cp_width_tr = 35
lat_tropics = 25
source_dlat = 5
T_hat_source = 36000
