# ==============================================================================
# global flags
# ==============================================================================
show_progress = true
interactive_mean = false
prescribed_wind = 'data/gaussians/mean-state.nc'

# ==============================================================================
# time stepping
# ==============================================================================
dt = 120
dt_output = 120
n_day = 21

# ==============================================================================
# vertical grid
# ==============================================================================
grid_bounds = [0, 60e3]
n_grid = 101

# ==============================================================================
# mean state profiles
# ==============================================================================
N0 = 0.02
rho0 = 1.2
boussinesq = false
H_rho = 7e3
latitude = 0

# ==============================================================================
# mean wind initialization
# ==============================================================================
# wind_init_method =
# u0 =
# v0 =
# z0 =
# sigma_uv =

# ==============================================================================
# pseudomomentum flux calculation
# ==============================================================================
shapiro_filter = true
proj_method = 'discrete'

# ==============================================================================
# viscosity and dissipation
# ==============================================================================
mu = 1e-3
dissipation = 1

# ==============================================================================
# ray volumes and propagation
# ==============================================================================
n_ray_max = 25000
min_pmf = 0
n_chromatic = -1
epsilon = 1

# ==============================================================================
# source and spectrum (parameters in this section are likely to be used by more
# than one source or spectrum type)
# ==============================================================================
source_type = 'deterministic'
spectrum_type = 'gaussians'
purge_mode = 'none'

dt_launch = 1
bc_mom_flux = 3e-3

r_launch = 10e3
dr_init = 250

dk_init = 1e-4
dl_init = 1e-4

wvl_hor_char = 100e3
direction = 0

# ==============================================================================
# 'coarse' source
# ==============================================================================
coarse_height = 0
coarse_width = 0

# ==============================================================================
# 'network' source
# ==============================================================================
model_path = 'data/coarsenet/model-5.jit'

# ==============================================================================
# 'gaussians' spectrum
# ==============================================================================
c_center = 0
c_width = 15
n_source = 54
