################################################################################
# global integration settings
################################################################################
mean_state_type = 'prescribed'
propagator_type = 'transient'
source_type = 'constant'
spectrum_type = 'from_file'

################################################################################
# input and output
################################################################################
average_output = true
prescribed_wind_file = 'data/icon-tropics/input/mean-state.nc'
spectrum_file = 'data/icon-tropics/input/spectrum.nc'

################################################################################
# time stepping
################################################################################
dt = 120
dt_output = 120
n_day = 30

################################################################################
# mean state
################################################################################
boussinesq = false
H_rho = 8e3
latitude = 0
n_grid = 401
N_ref = 0.02
rho_ref = 1.2
z_max = 70e3
z_min = 10e3

################################################################################
# viscosity and dissipation
################################################################################
dissipation = 1
mu = 1e-3

################################################################################
# gravity wave source and spectrum
################################################################################
c_max = 36
dt_launch = -1
extrinsic = false
flux_bc = 10e-3
n_source = 24 

################################################################################
# 'transient' propagator
################################################################################
cfl_mode = 'warn'
dr_init = 900
jitter = false
max_age = -1
max_dt_multiplier = 10
max_overshoot = 1.2
min_flux = 1e-8
n_chromatic = -1
n_increment = 0
n_max = 250
prune_by = 'energy'
shapiro_filter = true

################################################################################
# 'stochastic' source
################################################################################
epsilon = 1

################################################################################
# 'desaubies' spectrum
################################################################################
n_omega = 2
n_phi = 4
omega_hat_max = 5e-4
omega_hat_min = 1e-4
wvl_star = 2e3
