boussinesq = false
saturate_online = false
filter_pmf = true
hprop = false

dt = 120
n_day = 3

n_grid = 101
grid_max = 100e3

phi0 = 0
rhobar0 = 1.2
hh = 8.5e3

N0 = 0.01
alpha = 0.01
kappa = 1

uv_init_method = "sine_homogeneous"
u0 = 4
r0 = 40e3
sig_r = 10e3

source_method = "legacy"
n_ray_max = 100
n_ray = 60

wvl_hor_char = 50e3
wvl_ver_char = 5e3
direction = 0

dk_init = 1e-4
dl_init = 1e-4
r_m_area = 5e-5
r_init_bounds = [0, 15e3]
