# ==============================================================================
# global flags
# ==============================================================================
show_progress = true
interactive_mean = true

# ==============================================================================
# time stepping
# ==============================================================================
dt = 120
dt_output = 7200
n_day = 24

# ==============================================================================
# vertical grid
# ==============================================================================
grid_bounds = [0, 60e3]
n_grid = 101

# ==============================================================================
# mean state profiles
# ==============================================================================
N0 = 0.02
rho0 = 1.2
boussinesq = false
H_rho = 7e3
latitude = 0

# ==============================================================================
# mean wind initialization
# ==============================================================================
wind_init_method = 'gaussian'
u0 = 4
v0 = 0
z0 = 30e3
sigma_uv = 3e3

# ==============================================================================
# pseudomomentum flux calculation
# ==============================================================================
shapiro_filter = true
proj_method = 'discrete'

# ==============================================================================
# viscosity and dissipation
# ==============================================================================
mu = 0.5
dissipation = 1

# ==============================================================================
# ray volumes and propagation
# ==============================================================================
n_ray_max = 2500
epsilon = 1

# ==============================================================================
# source and spectrum (parameters in this section are likely to be used by more
# than one source or spectrum type)
# ==============================================================================
source_type = 'constant'
spectrum_type = 'gaussians'
purge = true

relaunch = true
bc_mom_flux = 1e-1

r_launch = 15e3
dr_init = 250

dk_init = 1e-4
dl_init = 1e-4

wvl_hor_char = 100e3
direction = 0

# ==============================================================================
# 'gaussians' spectrum
# ==============================================================================
c_center = 0
c_width = 15
n_source = 48
