[evaluation]
jet_period = 14
osc_period_min = 14
osc_period_max = 14
wvl_min = 5e3
wvl_max = 25e3
z_decay = 50e3
z_turn = 55e3

[strategies]
n_samples = 25

[generation]
dt_launch = 3600
lookahead = 172800
lookback = 172800
max_days = 10
n_packets = 5000000
speedup = 49

[architectures]
constrained = true
batch_norm_pos = 1
dropout_rate = 0.1
has_residual = true
max_kernel = 5

n_hidden_c = [4, 10, 16]
n_hidden_d = [32, 64, 128]
n_hidden_s = [128, 256, 512]

n_layers_c = [4, 8]
n_layers_d = [4, 10]
n_layers_s = 3

[training]
batch_size = 128
learning_rate = 1e-3
max_epochs = 3
max_hours = 3
noise_scale_c = 1
noise_scale_u = 0
weight_decay = 0