[scenarios]
ICON_component = 'v'
ICON_region = 'tropics'
n_columns = 25
noise_amplitude = 0
spectrum_type = 'gaussians'

[strategies]
dr_min = 500
dr_max = 5000
n_ensemble = 1
n_source_min = 8
n_source_max = 44