[scenarios]
components = 'xy'
ICON_region = 'tropics'
n_columns = 3
noise_amplitude = 0
spectrum_type = 'desaubies'

[strategies]
dr_min = 300
dr_max = 3000
n_dr = 10
n_ensemble = 25
n_n_source = 10
n_source_min = 8
n_source_max = 44