[scenarios]
noise_amplitude = 8
osc_amp_max = 55
osc_amp_min = 10
osc_top = 60e3
osc_bottom = 30e3
osc_period_max = 8
osc_period_min = 6
osc_wvl_bottom = 30e3
osc_wvl_top = 2e3
time_scale_decay = 6
time_scale_cutoff = 4

[strategies]
dr_min = 500
dr_max = 5000
n_ensemble = 25
n_source_min = 8
n_source_max = 44