[scenarios]

components = 'xy'
spectrum_type = 'mima'

[strategies]
debug = false
dr_min = 500
dr_max = 5000
n_dr = 10
n_ensemble = 5
n_n_source = 10
n_source_min = 4
n_source_max = 40

[generation]
dt_fine = 60
dt_coarse = 240
n_spinup = 5

[architectures]
batch_norm_pos = 1
block_depth = 3
n_blocks = 3
n_hidden = 256

[training]
batch_size = 256
cg_transform = 'robust'
learning_rate = 1e-3
max_epochs = 30
max_hours = 4
