[scenarios]

components = 'xy'
spectrum_type = 'mima'

[strategies]
debug = false
dr_min = 500
dr_max = 5000
n_dr = 10
n_ensemble = 5
n_n_source = 10
n_source_min = 4
n_source_max = 40

[generation]
dt_fine = 30
dt_coarse = 240

[architectures]
batch_norm_pos = [-1, 0, 1]
block_depth = [3, 6]
n_blocks = [2, 4]
n_hidden = [256, 1024]

[training]
batch_size = 32
in_transform = ['minmax', 'robust', 'z']
learning_rate = 1e-3
max_epochs = 50
max_hours = 5
n_smoothing = [0, 2]
