[scenarios]

components = 'xy'
spectrum_type = 'mima'

[strategies]
debug = false
dr_min = 500
dr_max = 5000
n_dr = 10
n_ensemble = 5
n_n_source = 10
n_source_min = 4
n_source_max = 40

[generation]
dt = 60
n_bins = 10

[architectures]
batch_norm_pos = [-1, 0, 1]
block_depth = [3, 6]
n_bins = 2
n_blocks = [2, 4]
n_hidden = [256, 1024]

[training]
batch_size = 32
dt = 240
in_transform = ['minmax', 'robust', 'z']
learning_rate = 1e-3
max_epochs = 10
max_hours = 5
n_smoothing = 2
output_scale = 1e4
