[scenarios]

components = 'xy'
spectrum_type = 'mima'

[strategies]
debug = false
dr_min = 500
dr_max = 5000
n_dr = 10
n_ensemble = 5
n_n_source = 10
n_source_min = 4
n_source_max = 40

[generation]
dt = 60
dt_output = 1200
n_bins = 10

[architectures]
beta_final = 6500
max_params = 4000000

[training]
M_transform = 'constant'
max_epochs = 50
max_hours = 1
min_delta = 0.00005
min_epochs = 10
n_smoothing = 8
patience = 10 