[scenarios]

components = 'xy'
spectrum_type = 'mima'

[strategies]
debug = false
dr_min = 500
dr_max = 5000
n_dr = 10
n_ensemble = 5
n_n_source = 10
n_source_min = 4
n_source_max = 40

[generation]
dt = 60
dt_output = 1200
n_bins = 12

[architectures]
learn_deltas = true
max_sink = 0.1

[training]
batch_size = 512
exp_name = 'cayuga'
loss_func = 'mse'
M_transform = 'constant'
max_epochs = 70
min_delta = 0.0002
n_online_test = 0
n_smoothing = 2
patience = 15