[scenarios]

components = 'xy'
spectrum_type = 'mima'

[strategies]
debug = false
dr_min = 500
dr_max = 5000
n_dr = 10
n_ensemble = 5
n_n_source = 10
n_source_min = 4
n_source_max = 40

[generation]
dt = 60
dt_output = 1800
n_bins = 10

[architectures]
batch_norm_pos = [0]
n_bins = [2]

n_convs = 3
n_hidden_conv = [16]
max_kernel = 5

n_blocks = [1]
n_hidden_lin = [256]
block_depth = 3

[training]
batch_size = 32
in_transform = ['z', 'robust', 'minmax']
learning_rate = 1e-3
max_epochs = 25
max_hours = 3
n_smoothing = 8
output_scale = 1e3
